In [1]:
import numpy as np
import numpy.linalg as LA
from sklearn import datasets
import matplotlib.pyplot as plt

In [2]:
np.set_printoptions(suppress=True, precision=5)

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

N, V = X.shape

### cetering 

In [4]:
Y = np.subtract(X , np.mean(X, axis=0))
Y.shape

(150, 4)

### power low method

In [5]:
Y.transpose().shape

(4, 150)

In [6]:
A = np.matmul(Y.transpose(), Y)
A

array([[102.16833,  -6.32267, 189.873  ,  76.92433],
       [ -6.32267,  28.30693, -49.1188 , -18.12427],
       [189.873  , -49.1188 , 464.3254 , 193.0458 ],
       [ 76.92433, -18.12427, 193.0458 ,  86.56993]])

In [7]:
c0 = np.ones([V, 1])
c0

array([[1.],
       [1.],
       [1.],
       [1.]])

In [8]:
Lambda = np.sqrt(np.sum(np.power(np.matmul(A, c0), 2)))
Lambda

940.7910034865554

In [9]:
Lambda = LA.norm(np.matmul(A, c0))
Lambda

940.7910034865554

In [10]:
c1 = (A@c0)/Lambda
c1

array([[ 0.38547],
       [-0.04811],
       [ 0.84836],
       [ 0.35971]])

In [11]:
iters = 0
while np.sqrt(np.sum(np.power(np.subtract(c1, c0), 2))) > 0.000001:
    iters +=1 
    c0 = np.copy(c1)
    Lambda = LA.norm(np.matmul(A, c0))
    c1 = (A@c0)/Lambda
print("iters:", iters)
print("Lambda:", Lambda, )
print("c1:", c1)

iters: 5
Lambda: 630.0080141991239
c1: [[ 0.36139]
 [-0.08452]
 [ 0.85667]
 [ 0.35829]]


In [12]:
A@c1 

array([[227.67645],
       [-53.24986],
       [539.70935],
       [225.72507]])

In [13]:
Lambda*c1

array([[227.67646],
       [-53.24985],
       [539.70934],
       [225.72506]])

In [14]:
A_10 = np.power(A, 10)
A_10

array([[1.23926e+20, 1.02095e+08, 6.09021e+22, 7.25500e+18],
       [1.02095e+08, 3.30315e+14, 8.17481e+16, 3.82476e+12],
       [6.09021e+22, 8.17481e+16, 4.65827e+26, 7.18793e+22],
       [7.25500e+18, 3.82476e+12, 7.18793e+22, 2.36413e+19]])

In [15]:
np.divide(A_10, A_10[0, 0])

array([[      1.     ,       0.     ,     491.43834,       0.05854],
       [      0.     ,       0.     ,       0.00066,       0.     ],
       [    491.43834,       0.00066, 3758904.80435,     580.01668],
       [      0.05854,       0.     ,     580.01668,       0.19077]])

In [16]:
A_20 = np.power(A, 20)
A_20

array([[1.53577e+40, 1.04233e+16, 3.70906e+45, 5.26350e+37],
       [1.04233e+16, 1.09108e+29, 6.68275e+33, 1.46288e+25],
       [3.70906e+45, 6.68275e+33, 2.16995e+53, 5.16663e+45],
       [5.26350e+37, 1.46288e+25, 5.16663e+45, 5.58910e+38]])

In [17]:
np.divide(A_20, A_20[0, 0])

array([[1.00000e+00, 6.78703e-25, 2.41512e+05, 3.42727e-03],
       [6.78703e-25, 7.10445e-12, 4.35140e-07, 9.52539e-16],
       [2.41512e+05, 4.35140e-07, 1.41294e+13, 3.36419e+05],
       [3.42727e-03, 9.52539e-16, 3.36419e+05, 3.63928e-02]])

In [18]:
A_30 = np.power(A, 30)
A_30

array([[1.90322e+60, 1.06416e+24, 2.25890e+68, 3.81867e+56],
       [1.06416e+24, 3.60400e+43, 5.46302e+50, 5.59517e+37],
       [2.25890e+68, 5.46302e+50, 1.01082e+80, 3.71373e+68],
       [3.81867e+56, 5.59517e+37, 3.71373e+68, 1.32133e+58]])

In [19]:
np.divide(A_20, A_30[0, 0])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.divide(A_20, A_30)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.divide(A_10, LA.norm(A_10))*1000000

array([[     0.26603,      0.     ,    130.73976,      0.01557],
       [     0.     ,      0.     ,      0.00018,      0.     ],
       [   130.73976,      0.00018, 999999.9591 ,    154.30469],
       [     0.01557,      0.     ,    154.30469,      0.05075]])

In [22]:
np.divide(A_20, LA.norm(A_20))*1000000

array([[      0.     ,       0.     ,       0.01709,       0.     ],
       [      0.     ,       0.     ,       0.     ,       0.     ],
       [      0.01709,       0.     , 1000000.     ,       0.02381],
       [      0.     ,       0.     ,       0.02381,       0.     ]])

In [23]:
np.divide(A_30, LA.norm(A_30))*1000000

array([[      0.,       0.,       0.,       0.],
       [      0.,       0.,       0.,       0.],
       [      0.,       0., 1000000.,       0.],
       [      0.,       0.,       0.,       0.]])