In [25]:
import warnings
import numpy as np
from sklearn import datasets
from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics.cluster import contingency_matrix

In [16]:
warnings.filterwarnings('ignore')
np.set_printoptions(suppress=True, linewidth=150, precision=2)

### Load data

In [6]:
iris= datasets.load_iris()
X = iris.data 
y = iris.target

### Normalization

In [8]:
me = np.mean(X, axis=0) # mean
ra = np.ptp(X, axis=0)  # range 
Y = np.divide(np.subtract(X, me), ra) # normilizad
Y.shape

(150, 4)

In [11]:
batch_size = 10
centers = np.array([Y[1, :], Y[52,:], Y[111, :]])
n_clusters = len(centers)
n_clusters

3

## Apply K-Means (batch)

In [27]:
for i in range(5):
    
    mbk = MiniBatchKMeans(n_clusters=n_clusters, batch_size=batch_size, init=centers)
    mbk.fit(Y)  # Compute K-mean
    ms = mbk.labels_
    
    cluster1 = X[np.where(ms==0)]
    cluster2 = X[np.where(ms==1)]
    cluster3 = X[np.where(ms==2)]
    
    mc1 = np.mean(cluster1, axis=0)
    mc2 = np.mean(cluster2, axis=0)
    mc3 = np.mean(cluster3, axis=0)
    
    
    d1 = 100*(np.divide(np.subtract(mc1, me), me))
    d2 = 100*(np.divide(np.subtract(mc2, me), me))
    d3 = 100*(np.divide(np.subtract(mc3, me), me))
    
    
    print("delta1:", d1, "#el:", cluster1.shape[0])
    print("delta2:", d2, "#el:", cluster2.shape[0])
    print("delta3:", d3, "#el:", cluster3.shape[0])
    print("inertia:", mbk.inertia_)
    cont_tb = contingency_matrix(labels_true=y, labels_pred=ms)
    print(cont_tb)
    
    print(" ")
    

delta1: [-14.33  12.12 -61.1  -79.49] #el: 50
delta2: [  0.73 -11.03  13.78   9.73] #el: 50
delta3: [13.6  -1.09 47.31 69.76] #el: 50
inertia: 7.5067034205293055
[[50  0  0]
 [ 0 46  4]
 [ 0  4 46]]
 
delta1: [-14.33  12.12 -61.1  -79.49] #el: 50
delta2: [ -0.01 -11.75  13.72  10.44] #el: 49
delta3: [14.06 -0.59 46.72 67.9 ] #el: 51
inertia: 7.225790569080509
[[50  0  0]
 [ 0 44  6]
 [ 0  5 45]]
 
delta1: [-14.33  12.12 -61.1  -79.49] #el: 50
delta2: [  0.87 -10.66  14.01  10.19] #el: 51
delta3: [13.72 -1.27 47.77 70.5 ] #el: 49
inertia: 7.634114806535553
[[50  0  0]
 [ 0 47  3]
 [ 0  4 46]]
 
delta1: [-14.33  12.12 -61.1  -79.49] #el: 50
delta2: [  0.77 -10.45  17.    18.24] #el: 61
delta3: [17.16  0.81 51.74 73.39] #el: 39
inertia: 7.189487700607209
[[50  0  0]
 [ 0 47  3]
 [ 0 14 36]]
 
delta1: [-14.33  12.12 -61.1  -79.49] #el: 50
delta2: [ -0.44 -11.75  14.63  13.3 ] #el: 51
delta3: [15.08 -0.14 47.11 67.27] #el: 49
inertia: 7.150360582288718
[[50  0  0]
 [ 0 43  7]
 [ 0  8 42]]
 